spring:
  application:
    name: api-call-example
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 30000
          test:
            connect-timeout: 3000
            read-timeout: 50000


